### ISSUE TITLE
set up Kanban board

### ISSUE THREAD

**Issue by bilalrajput09** [bilalrajput09/Catalog-of-my-things#34]
- Project Link : https://github.com/bilalrajput09/Catalog-of-my-things/projects/1
- 
- We are group of 3 guys. 
- Team usernames: 
- Team - 1 : bilalrajput09
- Team - 2 : AFakhriddinov 
- Team - 3 : mohamedSabry0

**Comment by KanzaTahreem** [comment]
# Changes Required 🔁

Hi @team

Good job so far ! I really appreciate the effort you put in!  **_However, there are few this that still need to be fixed. But you are almost there!_** 💪 🏁

![so close](https://media.tenor.com/3sCHnD_x2RIAAAAC/almost-there.gif)


## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Well organized cards
- ✅ Cards have points in the \[Xpt\] prefix
- ✅ Excellent description of the tasks
## Required Changes 🛑

- [ ] I noticed that an issue is present for for the following requirement, but a corresponding card is missing. Please make sure to add a card for third team member, @mohamedSabry0 ✨

![image](https://github.com/bilalrajput09/Catalog-of-my-things/assets/106119105/e3980385-4361-4ffa-a738-409d0c5bb956)

## Optional suggestions ❕

N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bilalrajput09** [comment]
![image](https://github.com/bilalrajput09/Catalog-of-my-things/assets/116716918/b9020d2d-fd8f-4bc3-a827-6fec4f27c9d9)

**Comment by bilalrajput09** [comment]
Fixed!!!

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @bilalrajput09, @mohamedSabry0 and @AFakhriddinov,

Good job so far!
✔️ Kanban columns are complete
✔️ Tasks are well assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] You are yet to fix the issue pointed out by the previous reviewer. If you filter out the tasks for the third partner, @mohamedSabry0, (you can visit the filter [here](https://github.com/bilalrajput09/Catalog-of-my-things/projects/1?card_filter_query=assignee%3Amohamedsabry0)). The task not part of his assignments. This is because that task is not part of the Kanban project. You need to add the issue to be a part of the Kanban project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bilalrajput09** [comment]
![image](https://github.com/bilalrajput09/Catalog-of-my-things/assets/116716918/57ae7f26-5b97-481e-8935-79206e72f59e)

**Comment by bilalrajput09** [comment]
Fixed!!!

**Comment by ichala** [comment]
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
